### ISSUE TITLE
滴滴声和循环播放多次逐渐变慢的问题

### ISSUE THREAD

**Issue by lajuchenghui** [Angelic47/LibWaveSynther#1]
我将这个算法移植到ac6921a和stm32h750都出现了的两个问题
1.播放的时候伴随了一些小声的滴滴声
2.让它自动循环播放一段时间后变慢

**Comment by Angelic47** [comment]
你好，关于你的这两个问题:
问题1: 这个问题我这里无法复现，建议直接录音发上来或者使用示波器测量波形, 同时粘贴移植后的代码；
问题2: 这个问题是否是“循环播放一段时间后，部分音轨不能同步，出现延迟”？假若是这个问题，问题的原因可能是音符表在播放结束后没有同步重新开始导致的，通过添加等待可以解决这个问题

**Comment by Angelic47** [comment]
关于该问题的问题1
经过我多天的研究，甚至找来了当年的ym2413音频合成芯片的参考设计原理图（年代过于久远，甚至只有模糊不清的扫描件，不再上传），大致结论如下：
原问题的描述中“滴滴声”实为啪啪响的爆破音。这个问题是由算法造成的，问题在于音符被关断的时候波形没有过零导致，直接输出16bit wav数据后使用波形查看器可见一个十分明显的纵向波形突变，故造成爆破音。该问题即使是x86平台上的演示工程也依然存在，仍然可用较好的耳机听出来（这里我使用了一个外置功放的专业监听耳机）。
其实即使是在早期的ym2413其实也是存在这个问题，为了避免这个问题，ym2413的参考设计原理图在输出端加入了一个**低通rc滤波**电容。通过这个滤波电容来将这样的纵向波形突变滤掉，同时还能让音频听起来变得更平滑，减少因为突变带来的金属感。外加受限于当时的设计，当年的音响设备解析率普遍不高，所以难以听出这样的细小爆破音。
但是由于现代化工业的进步，音响设备的解析率已经相当高，外加直接使用软件输出到喇叭dac的信号完全没有经过任何过滤，故即使是相同的音频合成算法，也会产生了这样的爆破音问题。
现代化商业/非商业合成器往往会在合成器的输出后端使用算法实现一个低通滤波，并实现混响等效果来增强输出，从而不会出现这样的爆破音问题。可因为本项目致力于高效，需求是能够在stm32f103上运行，故实在是没有多余的性能再实现滤波算法。
而最直接的解决的办法即是在dac输出后端**添加一个103-104的电容下拉到地**。

可增加电容的方法必将对音频输出的细节部分带来损失，然而stm32h750的性能其实已经相当的高，如果你有兴趣，可以自行套一层低通滤波算法来尝试软件上解决这个问题。也可以尝试增加混响器和eq，使声音更加圆润、饱满。

**Comment by lajuchenghui** [comment]
太强了 一个bug就是一段有趣的历史
